---
abstract: 'Resize easily all your pictures in one shot'
author:
  - 'Sandro CAZZANIGA'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: GPLv3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: resizer
no_index:
  directory:
    - t
    - inc
requires:
  Imager: 0.91
version: 1.0
